version: '3'
services:
  database:
    container_name: todo-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: todo_db
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/postgres_data
    networks:
      - todo-local-dev-network
    ports:
      - 7891:5432


networks:
  todo-local-dev-network:
    external: true